### ISSUE TITLE
Problema richiesta appelli

### ISSUE THREAD

**Issue by marcs7** [UnicApp/esse3-unica-api#1]
La richiesta appelliTot restituisce un array vuoto anche se la richiesta viene elaborata

**Comment by AsoStrife** [comment]
Ciao, sono state fatte modifiche alla struttura HTML di esse3, quindi il parsing non va a buon fine.
Purtroppo in questo periodo non ho tempo di aggiornare le API, spero nei prossimi mesi di fixare tutto.

Grazie mille 😊

Andrea Corriga (@AsoStrife)
Website: http://andreacorriga.com
Phone: (+39) 345 62 29 455

Da: Marco [mailto:notifications@github.com]
Inviato: giovedì 11 gennaio 2018 10:18
A: AsoStrife/unica-esse3-api <unica-esse3-api@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Oggetto: [AsoStrife/unica-esse3-api] Problema richiesta appelli (#1)


La richiesta appelliTot restituisce un array vuoto anche se la richiesta viene elaborata

**Comment by marcs7** [comment]
se il file ParseEsse3.php si occupa della ricerca dei dati all'interno dell'HTML posso provare a modificare per adattarlo alla nuova struttura

**Comment by AsoStrife** [comment]
Esatto. IL problema è sicuramente in parseLogin() ln. 36 (più altri eventuali che non ho avuto tempo di controllare).

Per la selezione della carriera hanno aggiunto un bottone nell’ultima colonna e rimosso altri link. Li sicuramente c’è da cambiare il parsing.

Grazie mille!

Andrea Corriga (@AsoStrife)
Microsoft Student Partner
http://andreacorriga.com

________________________________
Da: Marco <notifications@github.com>
Inviato: Thursday, January 11, 2018 10:43:36 AM
A: AsoStrife/unica-esse3-api
Cc: Andrea; Mention
Oggetto: Re: [AsoStrife/unica-esse3-api] Problema richiesta appelli (#1)


se il file ParseEsse3.php si occupa della ricerca dei dati all'interno dell'HTML posso provare a modificare per adattarlo alla nuova struttura

**Comment by marcs7** [comment]
vedo cosa riesco a modificare 
per il resto funziona tutto e restituisce i dati

**Comment by AsoStrife** [comment]
Ciao, abbiamo migrato il repository e aggiornato le API. 
Abbiamo aggiunto anche nuove applicazioni. Ti invito a guardare il tutto all'indirizzo: [https://github.com/UnicApp](https://github.com/UnicApp)
(Chiudo)
